export const RESET_STATE = 'RESET_STATE';

export const HELLO_BUTTON_CLICKED = 'HELLO_BUTTON_CLICKED';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_LOGOUT = 'LOGOUT';

export const CHANGE_PRIMARY_COLOR = 'CHANGE_PRIMARY_COLOR';
